### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by ojousima** [ruuvi/kicad-library#2]
For example [CERN-OHL-P v2.0 ](https://www.ohwr.org/project/cernohl/wikis/uploads/8a6b5d01f71c207c49493e4d114d61e6/cern_ohl_p_v2_howto.pdf) would allow anyone to use these symbols in their projects freely

**Comment by laurijamsa** [comment]
A free cultural license can be finally found here: https://github.com/ruuvi/kicad-library/blob/master/README.md
